### es info
GET http://127.0.0.1:9200/_cat/health?v&pretty
Authorization: Basic elastic ZAQ!2wsx

### es status
GET http://127.0.0.1:9200/_cluster/health
Authorization: Basic elastic ZAQ!2wsx

### index list
GET http://127.0.0.1:9200/_aliases?pretty=true
Authorization: Basic elastic ZAQ!2wsx

### index info
GET http://127.0.0.1:9200/article-search?pretty
Authorization: Basic elastic ZAQ!2wsx

### index delte
DELETE http://127.0.0.1:9200/article-search
Authorization: Basic elastic ZAQ!2wsx

### index clear
POST http://127.0.0.1:9200/article-search/_delete_by_query
Authorization: Basic elastic ZAQ!2wsx
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

