version: "3.9"

services:
  mysql:
    image: big_three/dev/mysql:latest
    build:
      context: ../../build/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=ZAQ!2wsx
    ports:
      - '3306:3306'

  elasticsearch:
    image: big_three/dev/elasticsearch:latest
    build:
      context: ../../build/elasticsearch
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=ZAQ!2wsx
    ports:
      - '9200:9200'
      - '9300:9300'

  skywalking-server:
    image: big_three/dev/skywalking-server:latest
    build:
      context: ../../build/skywalking/server
    container_name: skywalking-server
    ports:
      - '12800:12800'
      - '11800:11800'
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_ES_USER=elastic
      - SW_ES_PASSWORD=ZAQ!2wsx
      - SW_STORAGE_ES_INDEX_REPLICAS_NUMBER=0

  skywalking-ui:
    image: big_three/dev/skywalking-ui:latest
    build:
      context: ../../build/skywalking/ui
    container_name: skywalking-ui
    depends_on:
      skywalking-server:
        condition: service_healthy
    environment:
      - SW_OAP_ADDRESS=http://skywalking-server:12800
    ports:
      - '18080:8080'

  backend:
    image: big_three/dev/backend:latest
    build:
      context: ../../../backend
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - JAVA_OPTS=-Xmx128m -Xms128m -XX:+UseG1GC -Dspring.profiles.active=prod
      - SW_AGENT_NAME=big_three::backend
      - SW_LOGGING_DIR=/logs
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-server:11800

  frontend:
    image: big_three/dev/frontend:latest
    build:
      context: ../../../frontend
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '8080:80'
