spring:
  application:
    name: big-three
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
  servlet:
    context-path: /backend
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
mybatis:
  mapper-locations: classpath:mapper/**/*.xml