spring:
  main:
    allow-circular-references: true
  application:
    name: big-three
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8080
  servlet:
    context-path: /backend
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    root: INFO