spring:
  application:
    name: big-three
  profiles:
    active: dev
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always