apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2022-07-20T03:01:09Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: mysql-pv-volume
  resourceVersion: "56533"
  selfLink: /api/v1/persistentvolumes/mysql-pv-volume
  uid: 88de1691-3a0c-485a-97a1-23b16c01e694
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: default
    resourceVersion: "56095"
    uid: afcf08f1-33c1-466b-b30f-c4574ecfd52f
  hostPath:
    path: /mnt/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Bound
