apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2022-07-20T03:05:16Z"
  generation: 1
  name: mysql
  namespace: default
  resourceVersion: "57177"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/mysql
  uid: a1e0d8af-d7de-472e-8250-45aa12e84e5c
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: ghcr.io/zhaoyiqing97/big_three/mysql:latest
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mysql-5589b79d86
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: mysql-5589b79d86
  updatedReplicas: 1
