apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.154.132"],"port":30000,"protocol":"TCP","serviceName":"default:backend-nodeport","allNodes":true}]'
  name: backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-07-20T06:23:44Z"
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-backend
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx128m -Xms128m -XX:+UseG1GC -Dspring.profiles.active=prod
        image: ghcr.io/zhaoyiqing97/big_three/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          name: 8080tcp30000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
