name: "codiga"
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Codiga Check
    steps:
      - name: Check code meets quality standards
        id: codiga
        uses: codiga/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          codiga_api_token: ${{ secrets.CODIGA_API_TOKEN }}
          min_quality_grade: 'WARNING'
          min_quality_score: '50'
          max_defects_rate: '0.2'
          max_complex_functions_rate: '0.0001'
          max_long_functions_rate: '0.0001'
          project_name: 'github-action-example'
          max_timeout_sec: '600'
